name: PR Reviewed

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-pr:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
      - name: Label PR as ready for E2E
        if: github.event.review.state == 'approved'
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'ready-for-e2e'
